name: Matt Steele
author:
  name: Matt Steele
  email: matt@steele.blue
  uri: http://steele.blue
url: https://steele.blue
description: The personal website of Matt Steele
markdown: redcarpet
permalink: /:title/
distFolder: blog/
picture:
  source: "_img"
  output: "gen_img"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5]
      attr:
        class: "picturefilled"
      source_lg:
        media: "(min-width: 400px)"
        width: "768"
      source_default:
        width: "400"
gems:
  - jekyll-feed
feed:
  path: feed/atom.xml
